# Feature Engineering

주어진 정보에서 추가적인 정보를 이끌어내는 과정

데이터의 맥락을 이해해보고 어떤 것을 어떻게 조합하면 의미있는 정보가 될 것이다

In [101]:
import pandas as pd
import numpy as np
import seaborn as sns

In [102]:
dating_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dating.csv')

In [103]:
# 열 50개까지 볼 수 있도록
pd.set_option('display.max_columns',50)

In [104]:
dating_df.head()

,gender,age,age_o,race,race_o,importance_same_race,importance_same_religion,pref_o_attractive,pref_o_sincere,pref_o_intelligence,pref_o_funny,pref_o_ambitious,pref_o_shared_interests,attractive_o,sincere_o,intelligence_o,funny_o,ambitous_o,shared_interests_o,attractive_important,sincere_important,intellicence_important,funny_important,ambtition_important,shared_interests_important,attractive_partner,sincere_partner,intelligence_partner,funny_partner,ambition_partner,shared_interests_partner,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,match
0,female,21.0,27.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,35.0,20.0,20.0,20.0,0.0,5.0,6.0,8.0,8.0,8.0,8.0,6.0,15.0,20.0,20.0,15.0,15.0,15.0,6.0,9.0,7.0,7.0,6.0,5.0,0.14,3.0,2.0,7.0,6.0,0
1,female,21.0,22.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,60.0,0.0,0.0,40.0,0.0,0.0,7.0,8.0,10.0,7.0,7.0,5.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,8.0,7.0,8.0,5.0,6.0,0.54,3.0,2.0,7.0,5.0,0
2,female,21.0,22.0,Asian/PacificIslander/Asian-American,Asian/PacificIslander/Asian-American,2.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,10.0,10.0,10.0,10.0,10.0,10.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,8.0,9.0,8.0,5.0,7.0,0.16,3.0,2.0,7.0,NaN,1
3,female,21.0,23.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,30.0,5.0,15.0,40.0,5.0,5.0,7.0,8.0,9.0,8.0,9.0,8.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,6.0,8.0,7.0,6.0,8.0,0.61,3.0,2.0,7.0,6.0,1
4,female,21.0,24.0,Asian/PacificIslander/Asian-American,Latino/HispanicAmerican,2.0,4.0,30.0,10.0,20.0,10.0,10.0,20.0,8.0,7.0,9.0,6.0,9.0,7.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,6.0,7.0,7.0,6.0,6.0,0.21,3.0,2.0,6.0,6.0,1

In [105]:
dating_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8378 entries, 0 to 8377
Data columns (total 37 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   gender                         8378 non-null   object
 1   age                            8283 non-null   float64
 2   age_o                          8274 non-null   float64
 3   race                           8315 non-null   object
 4   race_o                         8305 non-null   object
 5   importance_same_race           8299 non-null   float64
 6   importance_same_religion       8299 non-null   float64
 7   pref_o_attractive              8289 non-null   float64
 8   pref_o_sincere                 8289 non-null   float64
 9   pref_o_intelligence            8289 non-null   float64
 10  pref_o_funny                   8280 non-null   float64
 11  pref_o_ambitious               8271 non-null   float64
 12  pref_o_shared_interests        8249 non-null   float64
 13  attractive_o                   8166 non-null   float64
 14  sincere_o                      8091 non-null   float64
 15  intelligence_o                 8072 non-null   float64
 16  funny_o                        8018 non-null   float64
 17  ambitous_o                     7656 non-null   float64
 18  shared_interests_o             7302 non-null   float64
 19  attractive_important           8299 non-null   float64
 20  sincere_important              8299 non-null   float64
 21  intellicence_important         8299 non-null   float64
 22  funny_important                8289 non-null   float64
 23  ambtition_important            8279 non-null   float64
 24  shared_interests_important     8257 non-null   float64
 25  attractive_partner             8176 non-null   float64
 26  sincere_partner                8101 non-null   float64
 27  intelligence_partner           8082 non-null   float64
 28  funny_partner                  8028 non-null   float64
 29  ambition_partner               7666 non-null   float64
 30  shared_interests_partner       7311 non-null   float64
 31  interests_correlate            8220 non-null   float64
 32  expected_happy_with_sd_people  8277 non-null   float64
 33  expected_num_interested_in_me  1800 non-null   float64
 34  like                           8138 non-null   float64
 35  guess_prob_liked               8069 non-null   float64
 36  match                          8378 non-null   int64
dtypes: float64(33), int64(1), object(3)
memory usage: 2.4+ MB

In [106]:
dating_df.describe()

,age,age_o,importance_same_race,importance_same_religion,pref_o_attractive,pref_o_sincere,pref_o_intelligence,pref_o_funny,pref_o_ambitious,pref_o_shared_interests,attractive_o,sincere_o,intelligence_o,funny_o,ambitous_o,shared_interests_o,attractive_important,sincere_important,intellicence_important,funny_important,ambtition_important,shared_interests_important,attractive_partner,sincere_partner,intelligence_partner,funny_partner,ambition_partner,shared_interests_partner,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,match
count,8283.000000,8274.000000,8299.000000,8299.000000,8289.000000,8289.000000,8289.000000,8280.000000,8271.000000,8249.000000,8166.000000,8091.000000,8072.000000,8018.000000,7656.000000,7302.000000,8299.000000,8299.000000,8299.000000,8289.000000,8279.000000,8257.000000,8176.000000,8101.000000,8082.000000,8028.000000,7666.000000,7311.000000,8220.000000,8277.000000,1800.000000,8138.000000,8069.000000,8378.000000
mean,26.358928,26.364999,3.784793,3.651645,22.495347,17.396867,20.270759,17.459714,10.685375,11.845930,6.190411,7.175256,7.369301,6.400599,6.778409,5.474870,22.514632,17.396389,20.265613,17.457043,10.682539,11.845111,6.189995,7.175164,7.368597,6.400598,6.777524,5.474559,0.196010,5.534131,5.570556,6.134087,5.207523,0.164717
std,3.566763,3.563648,2.845708,2.805237,12.569802,7.044003,6.782895,6.085526,6.126544,6.362746,1.950305,1.740575,1.550501,1.954078,1.794080,2.156163,12.587674,7.046700,6.783003,6.085239,6.124888,6.362154,1.950169,1.740315,1.550453,1.953702,1.794055,2.156363,0.303539,1.734059,4.762569,1.841285,2.129565,0.370947
min,18.000000,18.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.830000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,24.000000,24.000000,1.000000,1.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,5.000000,6.000000,6.000000,5.000000,6.000000,4.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,5.000000,6.000000,6.000000,5.000000,6.000000,4.000000,-0.020000,5.000000,2.000000,5.000000,4.000000,0.000000
50%,26.000000,26.000000,3.000000,3.000000,20.000000,18.370000,20.000000,18.000000,10.000000,10.640000,6.000000,7.000000,7.000000,7.000000,7.000000,6.000000,20.000000,18.180000,20.000000,18.000000,10.000000,10.640000,6.000000,7.000000,7.000000,7.000000,7.000000,6.000000,0.210000,6.000000,4.000000,6.000000,5.000000,0.000000
75%,28.000000,28.000000,6.000000,6.000000,25.000000,20.000000,23.810000,20.000000,15.000000,16.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,25.000000,20.000000,23.810000,20.000000,15.000000,16.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,0.430000,7.000000,8.000000,7.000000,7.000000,0.000000
max,55.000000,55.000000,10.000000,10.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,10.500000,10.000000,10.000000,11.000000,10.000000,10.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,0.910000,10.000000,20.000000,10.000000,10.000000,1.000000

In [107]:
# 컬럼 이름 변경
# pref_o: 상대방이 각각의 요소에 대해 얼마나 중요하게 생각하는가 (합: 100)
# _o: 상대방의 평가
# _important: 나에게 각 요소를 얼마나 중요하게 생각하는가
# _parner: 내가 상대방을 평가
dating_df.columns

Index(['gender', 'age', 'age_o', 'race', 'race_o', 'importance_same_race',
       'importance_same_religion', 'pref_o_attractive', 'pref_o_sincere',
       'pref_o_intelligence', 'pref_o_funny', 'pref_o_ambitious',
       'pref_o_shared_interests', 'attractive_o', 'sincere_o',
       'intelligence_o', 'funny_o', 'ambitous_o', 'shared_interests_o',
       'attractive_important', 'sincere_important', 'intellicence_important',
       'funny_important', 'ambtition_important', 'shared_interests_important',
       'attractive_partner', 'sincere_partner', 'intelligence_partner',
       'funny_partner', 'ambition_partner', 'shared_interests_partner',
       'interests_correlate', 'expected_happy_with_sd_people',
       'expected_num_interested_in_me', 'like', 'guess_prob_liked', 'match'],
      dtype='object')

In [109]:
# 내가 평가한 항목은 i, 상대방이 평가한 항목은 o로 바꿔줌
'string'.startswith('s')
'string'.endswith('j')

False

In [110]:
new_cols = []
for i in dating_df.columns:
  if i.startswith('pref_o'):
    i = i.replace('pref_o','o_important')
  elif i.endswith('_o'):
    i = 'o_score_' + i.replace('_o','')
  elif i.endswith ('important'):
    i = 'i_important_' + i.replace('_important','')
  elif i.endswith('_partner'):
    i = 'i_score_' + i.replace('_partner','')
  new_cols.append(i)

In [111]:
dating_df.columns = new_cols

In [112]:
pd.set_option('display.max_columns',50)

In [113]:
dating_df.head()

,gender,age,o_score_age,race,o_score_race,importance_same_race,importance_same_religion,o_important_attractive,o_important_sincere,o_important_intelligence,o_important_funny,o_important_ambitious,o_important_shared_interests,o_score_attractive,o_score_sincere,o_score_intelligence,o_score_funny,o_score_ambitous,o_score_shared_interests,i_important_attractive,i_important_sincere,i_important_intellicence,i_important_funny,i_important_ambtition,i_important_shared_interests,i_score_attractive,i_score_sincere,i_score_intelligence,i_score_funny,i_score_ambition,i_score_shared_interests,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,match
0,female,21.0,27.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,35.0,20.0,20.0,20.0,0.0,5.0,6.0,8.0,8.0,8.0,8.0,6.0,15.0,20.0,20.0,15.0,15.0,15.0,6.0,9.0,7.0,7.0,6.0,5.0,0.14,3.0,2.0,7.0,6.0,0
1,female,21.0,22.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,60.0,0.0,0.0,40.0,0.0,0.0,7.0,8.0,10.0,7.0,7.0,5.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,8.0,7.0,8.0,5.0,6.0,0.54,3.0,2.0,7.0,5.0,0
2,female,21.0,22.0,Asian/PacificIslander/Asian-American,Asian/PacificIslander/Asian-American,2.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,10.0,10.0,10.0,10.0,10.0,10.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,8.0,9.0,8.0,5.0,7.0,0.16,3.0,2.0,7.0,NaN,1
3,female,21.0,23.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,30.0,5.0,15.0,40.0,5.0,5.0,7.0,8.0,9.0,8.0,9.0,8.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,6.0,8.0,7.0,6.0,8.0,0.61,3.0,2.0,7.0,6.0,1
4,female,21.0,24.0,Asian/PacificIslander/Asian-American,Latino/HispanicAmerican,2.0,4.0,30.0,10.0,20.0,10.0,10.0,20.0,8.0,7.0,9.0,6.0,9.0,7.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,6.0,7.0,7.0,6.0,6.0,0.21,3.0,2.0,6.0,6.0,1

In [114]:
dating_df = dating_df.rename({'o_score_race':'race_o','o_score_age':'age_o'},axis=1)

# 결측치 처리

In [115]:
# 결측치 평균 확인
dating_df.isna().mean()

gender                           0.000000
age                              0.011339
age_o                            0.012413
race                             0.007520
race_o                           0.008713
importance_same_race             0.009429
importance_same_religion         0.009429
o_important_attractive           0.010623
o_important_sincere              0.010623
o_important_intelligence         0.010623
o_important_funny                0.011697
o_important_ambitious            0.012772
o_important_shared_interests     0.015397
o_score_attractive               0.025304
o_score_sincere                  0.034256
o_score_intelligence             0.036524
o_score_funny                    0.042970
o_score_ambitous                 0.086178
o_score_shared_interests         0.128432
i_important_attractive           0.009429
i_important_sincere              0.009429
i_important_intellicence         0.009429
i_important_funny                0.010623
i_important_ambtition            0.011817
i_important_shared_interests     0.014443
i_score_attractive               0.024111
i_score_sincere                  0.033063
i_score_intelligence             0.035331
i_score_funny                    0.041776
i_score_ambition                 0.084984
i_score_shared_interests         0.127357
interests_correlate              0.018859
expected_happy_with_sd_people    0.012055
expected_num_interested_in_me    0.785152
like                             0.028646
guess_prob_liked                 0.036882
match                            0.000000
dtype: float64

In [116]:
dating_df[dating_df['o_important_attractive'].isna()]

,gender,age,age_o,race,race_o,importance_same_race,importance_same_religion,o_important_attractive,o_important_sincere,o_important_intelligence,o_important_funny,o_important_ambitious,o_important_shared_interests,o_score_attractive,o_score_sincere,o_score_intelligence,o_score_funny,o_score_ambitous,o_score_shared_interests,i_important_attractive,i_important_sincere,i_important_intellicence,i_important_funny,i_important_ambtition,i_important_shared_interests,i_score_attractive,i_score_sincere,i_score_intelligence,i_score_funny,i_score_ambition,i_score_shared_interests,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,match
511,male,25.0,26.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,9.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,6.0,6.0,6.0,5.0,2.0,25.0,20.0,25.0,20.0,10.0,0.0,8.0,8.0,7.0,8.0,7.0,3.0,NaN,3.0,2.0,6.0,2.0,0
530,male,30.0,26.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,6.0,5.0,4.0,5.0,2.0,30.0,20.0,10.0,30.0,0.0,10.0,8.0,8.0,8.0,8.0,8.0,8.0,NaN,7.0,3.0,5.0,NaN,0
549,male,23.0,26.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,1.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5.0,8.0,5.0,8.0,3.0,20.0,25.0,20.0,15.0,10.0,10.0,7.0,10.0,9.0,8.0,9.0,NaN,NaN,6.0,3.0,8.0,6.0,0
568,male,24.0,26.0,European/Caucasian-American,European/Caucasian-American,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,6.0,5.0,4.0,4.0,3.0,25.0,35.0,30.0,10.0,0.0,0.0,5.0,6.0,6.0,4.0,7.0,6.0,NaN,3.0,1.0,5.0,2.0,0
587,male,24.0,26.0,European/Caucasian-American,European/Caucasian-American,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,6.0,7.0,4.0,5.0,2.0,25.0,15.0,25.0,25.0,15.0,15.0,5.0,5.0,5.0,5.0,6.0,5.0,NaN,7.0,5.0,5.0,5.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5649,male,30.0,NaN,Asian/PacificIslander/Asian-American,NaN,6.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,6.0,7.0,4.0,50.0,10.0,10.0,10.0,5.0,15.0,5.0,5.0,6.0,5.0,5.0,5.0,NaN,7.0,NaN,6.0,6.0,0
5669,male,27.0,NaN,European/Caucasian-American,NaN,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,8.0,8.0,9.0,7.0,7.0,8.0,30.0,20.0,15.0,15.0,8.0,12.0,5.0,6.0,7.0,6.0,7.0,7.0,NaN,5.0,NaN,6.0,6.0,0
5689,male,25.0,NaN,Asian/PacificIslander/Asian-American,NaN,10.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,10.0,15.0,20.0,15.0,10.0,8.0,9.0,7.0,7.0,7.0,8.0,NaN,5.0,NaN,7.0,6.0,0
5709,male,26.0,NaN,Asian/PacificIslander/Asian-American,NaN,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0,6.0,5.0,4.0,4.0,3.0,25.0,20.0,10.0,20.0,15.0,10.0,9.0,9.0,9.0,9.0,7.0,7.0,NaN,6.0,NaN,8.0,7.0,0
5729,male,29.0,NaN,European/Caucasian-American,NaN,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,9.0,8.0,7.0,9.0,7.0,10.0,25.0,15.0,20.0,20.0,10.0,10.0,8.0,9.0,7.0,7.0,6.0,8.0,NaN,6.0,NaN,8.0,6.0,1

In [117]:
# 결측치 제거
drop_cols = []
for i in dating_df.columns:
  if i.startswith('o_important'):
    drop_cols.append(i)
  elif i.startswith('i_important'):
    drop_cols.append(i)

In [118]:
drop_cols

['o_important_attractive',
 'o_important_sincere',
 'o_important_intelligence',
 'o_important_funny',
 'o_important_ambitious',
 'o_important_shared_interests',
 'i_important_attractive',
 'i_important_sincere',
 'i_important_intellicence',
 'i_important_funny',
 'i_important_ambtition',
 'i_important_shared_interests']

In [121]:
# 상대방과 내가 중요하게 생각하는 요소 결측치 제거
dating_df = dating_df.dropna(subset = drop_cols)

In [122]:
dating_df.isna().mean()

gender                           0.000000
age                              0.002706
age_o                            0.002706
race                             0.000000
race_o                           0.000000
importance_same_race             0.000000
importance_same_religion         0.000000
o_important_attractive           0.000000
o_important_sincere              0.000000
o_important_intelligence         0.000000
o_important_funny                0.000000
o_important_ambitious            0.000000
o_important_shared_interests     0.000000
o_score_attractive               0.022755
o_score_sincere                  0.031488
o_score_intelligence             0.034071
o_score_funny                    0.040590
o_score_ambitous                 0.084625
o_score_shared_interests         0.127798
i_important_attractive           0.000000
i_important_sincere              0.000000
i_important_intellicence         0.000000
i_important_funny                0.000000
i_important_ambtition            0.000000
i_important_shared_interests     0.000000
i_score_attractive               0.022755
i_score_sincere                  0.031488
i_score_intelligence             0.034071
i_score_funny                    0.040590
i_score_ambition                 0.084625
i_score_shared_interests         0.127798
interests_correlate              0.000000
expected_happy_with_sd_people    0.002706
expected_num_interested_in_me    0.788438
like                             0.027306
guess_prob_liked                 0.035301
match                            0.000000
dtype: float64

In [126]:
# 결측치 -99로 대체
dating_df = dating_df.fillna(-99)

# Outlier

In [127]:
dating_df.describe()

,age,age_o,importance_same_race,importance_same_religion,o_important_attractive,o_important_sincere,o_important_intelligence,o_important_funny,o_important_ambitious,o_important_shared_interests,o_score_attractive,o_score_sincere,o_score_intelligence,o_score_funny,o_score_ambitous,o_score_shared_interests,i_important_attractive,i_important_sincere,i_important_intellicence,i_important_funny,i_important_ambtition,i_important_shared_interests,i_score_attractive,i_score_sincere,i_score_intelligence,i_score_funny,i_score_ambition,i_score_shared_interests,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,match
count,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000
mean,26.034932,26.034932,3.776753,3.658303,22.320451,17.433629,20.266113,17.446224,10.705183,11.872082,3.803555,3.841882,3.757380,2.128106,-2.159533,-7.869065,22.320451,17.433629,20.266113,17.446224,10.705183,11.872082,3.803493,3.841882,3.757380,2.127983,-2.159533,-7.869065,0.198866,5.244649,-76.879090,3.270812,1.537761,0.164822
std,7.418562,7.418562,2.844297,2.807314,12.398470,7.017378,6.770061,6.068068,6.101937,6.351582,15.804941,18.622449,19.358834,20.888796,29.495408,34.942787,12.398470,7.017378,6.770061,6.068068,6.101937,6.351582,15.804916,18.622449,19.358834,20.888746,29.495408,34.942787,0.302338,5.697854,42.761973,17.230563,19.345369,0.371042
min,-99.000000,-99.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-0.830000,-99.000000,-99.000000,-99.000000,-99.000000,0.000000
25%,24.000000,24.000000,1.000000,1.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,5.000000,6.000000,6.000000,5.000000,5.000000,3.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,5.000000,6.000000,6.000000,5.000000,5.000000,3.000000,-0.010000,5.000000,-99.000000,5.000000,4.000000,0.000000
50%,26.000000,26.000000,3.000000,3.000000,20.000000,18.370000,20.000000,18.000000,10.000000,10.870000,6.000000,7.000000,7.000000,6.000000,7.000000,5.000000,20.000000,18.370000,20.000000,18.000000,10.000000,10.870000,6.000000,7.000000,7.000000,6.000000,7.000000,5.000000,0.220000,6.000000,-99.000000,6.000000,5.000000,0.000000
75%,28.000000,28.000000,6.000000,6.000000,25.000000,20.000000,23.260000,20.000000,15.000000,16.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,25.000000,20.000000,23.260000,20.000000,15.000000,16.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,0.430000,7.000000,-99.000000,7.000000,7.000000,0.000000
max,55.000000,55.000000,10.000000,10.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,10.500000,10.000000,10.000000,11.000000,10.000000,10.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,0.910000,10.000000,20.000000,10.000000,10.000000,1.000000

In [128]:
# 10점 만점에 10.5라고 잘못 작성한 사람 있음
dating_df['o_score_attractive'].sort_values()

6069   -99.0
6031   -99.0
95     -99.0
8302   -99.0
8359   -99.0
        ...
3622    10.0
7452    10.0
7437    10.0
7432    10.0
6216    10.5
Name: o_score_attractive, Length: 8130, dtype: float64

In [129]:
dating_df['o_score_funny'].sort_values()

6162   -99.0
6139   -99.0
6137   -99.0
6306   -99.0
6324   -99.0
        ...
193     10.0
5345    10.0
1526    10.0
4940    10.0
6608    11.0
Name: o_score_funny, Length: 8130, dtype: float64

In [130]:
# 10보다 큰 값은 10으로 변경
dating_df['o_score_attractive'].apply(lambda x : 10 if x > 10 else x)

0        6.0
1        7.0
2       10.0
3        7.0
4        8.0
        ...
8372     8.0
8373    10.0
8374     6.0
8376     5.0
8377     8.0
Name: o_score_attractive, Length: 8130, dtype: float64

In [131]:
dating_df['o_score_attractive'].apply(lambda x : 10 if x > 10 else x).max()

10.0

In [132]:
dating_df['o_score_funny'].apply(lambda x : 10 if x > 10 else x)

0        8.0
1        7.0
2       10.0
3        8.0
4        6.0
        ...
8372     7.0
8373     2.0
8374     3.0
8376     5.0
8377     7.0
Name: o_score_funny, Length: 8130, dtype: float64

In [134]:
# o_important 으로 시작하는 컬럼 o_imp 변수에 담기
o_imp = []
for i in dating_df.columns:
  if i.startswith('o_important'):
    o_imp.append(i)

In [135]:
o_imp

['o_important_attractive',
 'o_important_sincere',
 'o_important_intelligence',
 'o_important_funny',
 'o_important_ambitious',
 'o_important_shared_interests']

In [139]:
# o_important 의 컬럼별 합계
# o_imporant의 합계는 100인데, 100이 넘는 값들이 있음
dating_df['o_imp_sum'] = dating_df[o_imp].sum(axis=1)

In [140]:
i_imp = []
for i in dating_df.columns:
  if i.startswith('i_important'):
    i_imp.append(i)

In [141]:
i_imp

['i_important_attractive',
 'i_important_sincere',
 'i_important_intellicence',
 'i_important_funny',
 'i_important_ambtition',
 'i_important_shared_interests']

In [142]:
# i_important 의 컬럼별 합계
# i_imporant의 합계는 100인데, 100이 넘는 값들이 있음
dating_df['i_imp_sum'] = dating_df[i_imp].sum(axis=1)

In [143]:
dating_df

,gender,age,age_o,race,race_o,importance_same_race,importance_same_religion,o_important_attractive,o_important_sincere,o_important_intelligence,o_important_funny,o_important_ambitious,o_important_shared_interests,o_score_attractive,o_score_sincere,o_score_intelligence,o_score_funny,o_score_ambitous,o_score_shared_interests,i_important_attractive,i_important_sincere,i_important_intellicence,i_important_funny,i_important_ambtition,i_important_shared_interests,i_score_attractive,i_score_sincere,i_score_intelligence,i_score_funny,i_score_ambition,i_score_shared_interests,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,match,o_imp_sum,i_imp_sum
0,female,21.0,27.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,35.0,20.0,20.0,20.0,0.0,5.0,6.0,8.0,8.0,8.0,8.0,6.0,15.0,20.0,20.0,15.0,15.0,15.0,6.0,9.0,7.0,7.0,6.0,5.0,0.14,3.0,2.0,7.0,6.0,0,100.0,100.0
1,female,21.0,22.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,60.0,0.0,0.0,40.0,0.0,0.0,7.0,8.0,10.0,7.0,7.0,5.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,8.0,7.0,8.0,5.0,6.0,0.54,3.0,2.0,7.0,5.0,0,100.0,100.0
2,female,21.0,22.0,Asian/PacificIslander/Asian-American,Asian/PacificIslander/Asian-American,2.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,10.0,10.0,10.0,10.0,10.0,10.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,8.0,9.0,8.0,5.0,7.0,0.16,3.0,2.0,7.0,-99.0,1,100.0,100.0
3,female,21.0,23.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,30.0,5.0,15.0,40.0,5.0,5.0,7.0,8.0,9.0,8.0,9.0,8.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,6.0,8.0,7.0,6.0,8.0,0.61,3.0,2.0,7.0,6.0,1,100.0,100.0
4,female,21.0,24.0,Asian/PacificIslander/Asian-American,Latino/HispanicAmerican,2.0,4.0,30.0,10.0,20.0,10.0,10.0,20.0,8.0,7.0,9.0,6.0,9.0,7.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,6.0,7.0,7.0,6.0,6.0,0.21,3.0,2.0,6.0,6.0,1,100.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8372,male,25.0,24.0,European/Caucasian-American,European/Caucasian-American,1.0,1.0,10.0,15.0,30.0,20.0,15.0,10.0,8.0,8.0,7.0,7.0,8.0,6.0,70.0,0.0,15.0,15.0,0.0,0.0,7.0,5.0,5.0,5.0,6.0,-99.0,0.28,10.0,-99.0,4.0,4.0,0,100.0,100.0
8373,male,25.0,26.0,European/Caucasian-American,Latino/HispanicAmerican,1.0,1.0,10.0,10.0,30.0,20.0,10.0,15.0,10.0,5.0,3.0,2.0,6.0,5.0,70.0,0.0,15.0,15.0,0.0,0.0,3.0,5.0,5.0,5.0,-99.0,-99.0,0.64,10.0,-99.0,2.0,5.0,0,95.0,100.0
8374,male,25.0,24.0,European/Caucasian-American,Other,1.0,1.0,50.0,20.0,10.0,5.0,10.0,5.0,6.0,3.0,7.0,3.0,7.0,2.0,70.0,0.0,15.0,15.0,0.0,0.0,4.0,6.0,8.0,4.0,4.0,-99.0,0.71,10.0,-99.0,4.0,4.0,0,100.0,100.0
8376,male,25.0,22.0,European/Caucasian-American,Asian/PacificIslander/Asian-American,1.0,1.0,10.0,25.0,25.0,10.0,10.0,20.0,5.0,7.0,5.0,5.0,3.0,6.0,70.0,0.0,15.0,15.0,0.0,0.0,4.0,6.0,5.0,4.0,-99.0,5.0,0.62,10.0,-99.0,5.0,5.0,0,100.0,100.0
8377,male,25.0,22.0,European/Caucasian-American,Asian/PacificIslander/Asian-American,1.0,1.0,20.0,20.0,10.0,15.0,5.0,30.0,8.0,8.0,7.0,7.0,7.0,7.0,70.0,0.0,15.0,15.0,0.0,0.0,3.0,7.0,6.0,4.0,8.0,1.0,0.01,10.0,-99.0,4.0,5.0,0,100.0,100.0

In [144]:
# imp의 sum이 100이 아닌 경우 필터링
dating_df[dating_df['o_imp_sum'] != 100]

,gender,age,age_o,race,race_o,importance_same_race,importance_same_religion,o_important_attractive,o_important_sincere,o_important_intelligence,o_important_funny,o_important_ambitious,o_important_shared_interests,o_score_attractive,o_score_sincere,o_score_intelligence,o_score_funny,o_score_ambitous,o_score_shared_interests,i_important_attractive,i_important_sincere,i_important_intellicence,i_important_funny,i_important_ambtition,i_important_shared_interests,i_score_attractive,i_score_sincere,i_score_intelligence,i_score_funny,i_score_ambition,i_score_shared_interests,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,match,o_imp_sum,i_imp_sum
7,female,21.0,27.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,33.33,11.11,11.11,11.11,11.11,22.22,6.0,7.0,5.0,6.0,8.0,6.0,15.0,20.0,20.0,15.0,15.0,15.0,4.0,9.0,7.0,6.0,5.0,6.0,0.50,3.0,2.0,6.0,7.0,0,99.99,100.0
17,female,24.0,27.0,European/Caucasian-American,European/Caucasian-American,2.0,5.0,33.33,11.11,11.11,11.11,11.11,22.22,7.0,7.0,7.0,7.0,7.0,5.0,45.0,5.0,25.0,20.0,0.0,5.0,5.0,8.0,7.0,5.0,9.0,5.0,0.07,4.0,5.0,5.0,6.0,0,99.99,100.0
27,female,25.0,27.0,European/Caucasian-American,European/Caucasian-American,8.0,4.0,33.33,11.11,11.11,11.11,11.11,22.22,4.0,5.0,6.0,4.0,6.0,4.0,35.0,10.0,35.0,10.0,10.0,0.0,7.0,9.0,9.0,8.0,9.0,7.0,0.29,4.0,2.0,8.0,7.0,0,99.99,100.0
37,female,23.0,27.0,European/Caucasian-American,European/Caucasian-American,1.0,1.0,33.33,11.11,11.11,11.11,11.11,22.22,6.0,7.0,8.0,6.0,6.0,5.0,20.0,20.0,20.0,20.0,10.0,10.0,5.0,9.0,9.0,5.0,9.0,7.0,0.15,1.0,2.0,6.0,6.0,0,99.99,100.0
47,female,21.0,27.0,European/Caucasian-American,European/Caucasian-American,8.0,1.0,33.33,11.11,11.11,11.11,11.11,22.22,5.0,5.0,6.0,5.0,5.0,5.0,20.0,5.0,25.0,25.0,10.0,15.0,5.0,5.0,7.0,6.0,7.0,5.0,0.07,7.0,10.0,6.0,4.0,0,99.99,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8343,male,27.0,23.0,Black/AfricanAmerican,European/Caucasian-American,2.0,1.0,20.00,25.00,25.00,30.00,5.00,5.00,7.0,6.0,6.0,5.0,5.0,-99.0,40.0,20.0,20.0,20.0,0.0,0.0,8.0,5.0,5.0,7.0,7.0,5.0,0.53,3.0,-99.0,7.0,3.0,0,110.00,100.0
8351,male,27.0,26.0,Black/AfricanAmerican,Latino/HispanicAmerican,2.0,1.0,10.00,10.00,30.00,20.00,10.00,15.00,10.0,5.0,8.0,6.0,9.0,8.0,40.0,20.0,20.0,20.0,0.0,0.0,7.0,7.0,7.0,7.0,7.0,7.0,0.41,3.0,-99.0,8.0,1.0,0,95.00,100.0
8364,male,25.0,30.0,European/Caucasian-American,Latino/HispanicAmerican,1.0,1.0,15.00,20.00,20.00,20.00,5.00,10.00,6.0,5.0,4.0,3.0,6.0,5.0,70.0,0.0,15.0,15.0,0.0,0.0,6.0,9.0,9.0,9.0,8.0,8.0,0.43,10.0,-99.0,7.0,6.0,0,90.00,100.0
8365,male,25.0,23.0,European/Caucasian-American,European/Caucasian-American,1.0,1.0,20.00,25.00,25.00,30.00,5.00,5.00,8.0,7.0,6.0,7.0,7.0,2.0,70.0,0.0,15.0,15.0,0.0,0.0,5.0,8.0,8.0,7.0,7.0,8.0,0.47,10.0,-99.0,6.0,7.0,0,110.00,100.0
8373,male,25.0,26.0,European/Caucasian-American,Latino/HispanicAmerican,1.0,1.0,10.00,10.00,30.00,20.00,10.00,15.00,10.0,5.0,3.0,2.0,6.0,5.0,70.0,0.0,15.0,15.0,0.0,0.0,3.0,5.0,5.0,5.0,-99.0,-99.0,0.64,10.0,-99.0,2.0,5.0,0,95.00,100.0

사람마다 다르게 준 중요도 점수를 "같은 기준"으로 바꾸는 작업

사람마다 준 점수 총합이 다르기 때문에, 같은 기준(합 100) 으로 맞춰서 공정하게 비교하려고

(100 / 총합) * 각 점수 식으로 정규화

In [145]:
# 모든 사람들이 합이 100이 되는 조건을 만들어줌 -> 가중치를 통해
# (100/sum) * 95 <-- 각 항목의 값
# sum이 100일 경우에는 가중치가 없기 때문에 결과가 1이 나옴
dating_df[o_imp] = dating_df.apply(lambda x : (100 / x['o_imp_sum']) * x[o_imp] , axis=1)

In [146]:
dating_df[o_imp].sum(axis=1)

0       100.0
1       100.0
2       100.0
3       100.0
4       100.0
        ...
8372    100.0
8373    100.0
8374    100.0
8376    100.0
8377    100.0
Length: 8130, dtype: float64

In [147]:
dating_df[i_imp] = dating_df.apply(lambda x : (100 / x['i_imp_sum']) * x[i_imp] , axis=1)

In [148]:
dating_df[i_imp].sum(axis=1)

0       100.0
1       100.0
2       100.0
3       100.0
4       100.0
        ...
8372    100.0
8373    100.0
8374    100.0
8376    100.0
8377    100.0
Length: 8130, dtype: float64

In [149]:
# o_imp_sum, i_imp_sum 두 컬럼의 합을 100으로 맞춰뒀기 때문에 더이상 필요 없음 -> 삭제
dating_df.drop(['o_imp_sum','i_imp_sum'], axis=1, inplace=True)

In [44]:
dating_df.head()

,gender,age,age_o,race,race_o,importance_same_race,importance_same_religion,o_important_attractive,o_important_sincere,o_important_intelligence,o_important_funny,o_important_ambitious,o_important_shared_interests,o_score_attractive,o_score_sincere,o_score_intelligence,o_score_funny,o_score_ambitous,o_score_shared_interests,i_important_attractive,i_important_sincere,i_important_intellicence,i_important_funny,i_important_ambtition,i_important_shared_interests,i_score_attractive,i_score_sincere,i_score_intelligence,i_score_funny,i_score_ambition,i_score_shared_interests,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,match
0,female,21.0,27.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,35.0,20.0,20.0,20.0,0.0,5.0,6.0,8.0,8.0,8.0,8.0,6.0,15.0,20.0,20.0,15.0,15.0,15.0,6.0,9.0,7.0,7.0,6.0,5.0,0.14,3.0,2.0,7.0,6.0,0
1,female,21.0,22.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,60.0,0.0,0.0,40.0,0.0,0.0,7.0,8.0,10.0,7.0,7.0,5.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,8.0,7.0,8.0,5.0,6.0,0.54,3.0,2.0,7.0,5.0,0
2,female,21.0,22.0,Asian/PacificIslander/Asian-American,Asian/PacificIslander/Asian-American,2.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,10.0,10.0,10.0,10.0,10.0,10.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,8.0,9.0,8.0,5.0,7.0,0.16,3.0,2.0,7.0,-99.0,1
3,female,21.0,23.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,30.0,5.0,15.0,40.0,5.0,5.0,7.0,8.0,9.0,8.0,9.0,8.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,6.0,8.0,7.0,6.0,8.0,0.61,3.0,2.0,7.0,6.0,1
4,female,21.0,24.0,Asian/PacificIslander/Asian-American,Latino/HispanicAmerican,2.0,4.0,30.0,10.0,20.0,10.0,10.0,20.0,8.0,7.0,9.0,6.0,9.0,7.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,6.0,7.0,7.0,6.0,6.0,0.21,3.0,2.0,6.0,6.0,1

# Age

In [151]:
def age_func(x):
  if x['age'] == -99:
    return -99
  elif x['age_o'] == -99:
    return -99
  elif x['gender'] == 'female':
    return x['age_o'] - x['age']
  else:
    return x['age'] - x['age_o']

In [153]:
dating_df['age_gap'] = dating_df.apply(age_func, axis=1)

In [154]:
dating_df['age_gap']

0       6.0
1       1.0
2       1.0
3       2.0
4       3.0
       ...
8372    1.0
8373   -1.0
8374    1.0
8376    3.0
8377    3.0
Name: age_gap, Length: 8130, dtype: float64

In [155]:
# 남자와 여자 중 누가 더 나이가 많은지 판단하기 위함
dating_df['age_gap_dir'] = dating_df['age_gap'].apply(lambda x : 'positive' if x > 10 else 'negative' if x < 0 else 'zero')

In [156]:
# 나이차 절댓값 처리
dating_df['age_gap'] = abs(dating_df['age_gap'])

In [157]:
dating_df.head()

,gender,age,age_o,race,race_o,importance_same_race,importance_same_religion,o_important_attractive,o_important_sincere,o_important_intelligence,o_important_funny,o_important_ambitious,o_important_shared_interests,o_score_attractive,o_score_sincere,o_score_intelligence,o_score_funny,o_score_ambitous,o_score_shared_interests,i_important_attractive,i_important_sincere,i_important_intellicence,i_important_funny,i_important_ambtition,i_important_shared_interests,i_score_attractive,i_score_sincere,i_score_intelligence,i_score_funny,i_score_ambition,i_score_shared_interests,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,match,age_gap,age_gap_dir
0,female,21.0,27.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,35.0,20.0,20.0,20.0,0.0,5.0,6.0,8.0,8.0,8.0,8.0,6.0,15.0,20.0,20.0,15.0,15.0,15.0,6.0,9.0,7.0,7.0,6.0,5.0,0.14,3.0,2.0,7.0,6.0,0,6.0,zero
1,female,21.0,22.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,60.0,0.0,0.0,40.0,0.0,0.0,7.0,8.0,10.0,7.0,7.0,5.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,8.0,7.0,8.0,5.0,6.0,0.54,3.0,2.0,7.0,5.0,0,1.0,zero
2,female,21.0,22.0,Asian/PacificIslander/Asian-American,Asian/PacificIslander/Asian-American,2.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,10.0,10.0,10.0,10.0,10.0,10.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,8.0,9.0,8.0,5.0,7.0,0.16,3.0,2.0,7.0,-99.0,1,1.0,zero
3,female,21.0,23.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,30.0,5.0,15.0,40.0,5.0,5.0,7.0,8.0,9.0,8.0,9.0,8.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,6.0,8.0,7.0,6.0,8.0,0.61,3.0,2.0,7.0,6.0,1,2.0,zero
4,female,21.0,24.0,Asian/PacificIslander/Asian-American,Latino/HispanicAmerican,2.0,4.0,30.0,10.0,20.0,10.0,10.0,20.0,8.0,7.0,9.0,6.0,9.0,7.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,6.0,7.0,7.0,6.0,6.0,0.21,3.0,2.0,6.0,6.0,1,3.0,zero

# Race

In [158]:
# 인종이 같으면 1, 다르면 0
dating_df['same_race'] = (dating_df['race'] == dating_df['race_o']).astype('int')

In [52]:
# 같은 인종 여부에 같은 인종 중요도를 곱함
# 하지만 인종이 같지 않을 경우에는 0을 곱하기 때문에 결과가 항상 0이 됨
#dating_df['same_race'] * dating_df['importance_same_race']

In [159]:
# 0을 -1로 바꿈
dating_df['same_race'] = dating_df['same_race'].replace({0:-1})

In [160]:
dating_df['same_race'].value_counts()

same_race
-1    4844
 1    3286
Name: count, dtype: int64

In [161]:
dating_df['same_race_point'] = dating_df['same_race'] * dating_df['importance_same_race']

In [162]:
dating_df['same_race_point'].head(30)

0    -2.0
1    -2.0
2     2.0
3    -2.0
4    -2.0
5    -2.0
6    -2.0
7    -2.0
8    -2.0
9    -2.0
10    2.0
11    2.0
12   -2.0
13    2.0
14   -2.0
15    2.0
16    2.0
17    2.0
18    2.0
19    2.0
20    8.0
21    8.0
22   -8.0
23    8.0
24   -8.0
25    8.0
26    8.0
27    8.0
28    8.0
29    8.0
Name: same_race_point, dtype: float64

# Rating

In [163]:
# i_important, i_score, o_imporatnt, o_score 각각의 컬럼을 리스트로 모음
o_important = []
o_score = []
i_important = []
i_score = []

for i in dating_df.columns:
  if i.startswith('o_important'):
    o_important.append(i)
  elif i.startswith('o_score'):
    o_score.append(i)
  elif i.startswith('i_important'):
    i_important.append(i)
  elif i.startswith('i_score'):
    i_score.append(i)

In [164]:
# o_important의 0값을 99로 변경
dating_df[o_important].replace({0:-99})

,o_important_attractive,o_important_sincere,o_important_intelligence,o_important_funny,o_important_ambitious,o_important_shared_interests
0,35.000000,20.000000,20.000000,20.000000,-99.000000,5.000000
1,60.000000,-99.000000,-99.000000,40.000000,-99.000000,-99.000000
2,19.000000,18.000000,19.000000,18.000000,14.000000,12.000000
3,30.000000,5.000000,15.000000,40.000000,5.000000,5.000000
4,30.000000,10.000000,20.000000,10.000000,10.000000,20.000000
...,...,...,...,...,...,...
8372,10.000000,15.000000,30.000000,20.000000,15.000000,10.000000
8373,10.526316,10.526316,31.578947,21.052632,10.526316,15.789474
8374,50.000000,20.000000,10.000000,5.000000,10.000000,5.000000
8376,10.000000,25.000000,25.000000,10.000000,10.000000,20.000000
8377,20.000000,20.000000,10.000000,15.000000,5.000000,30.000000

In [165]:
# o_important의 0값을 99로 변경
dating_df[i_important].replace({0:-99})

,i_important_attractive,i_important_sincere,i_important_intellicence,i_important_funny,i_important_ambtition,i_important_shared_interests
0,15.0,20.0,20.0,15.0,15.0,15.0
1,15.0,20.0,20.0,15.0,15.0,15.0
2,15.0,20.0,20.0,15.0,15.0,15.0
3,15.0,20.0,20.0,15.0,15.0,15.0
4,15.0,20.0,20.0,15.0,15.0,15.0
...,...,...,...,...,...,...
8372,70.0,-99.0,15.0,15.0,-99.0,-99.0
8373,70.0,-99.0,15.0,15.0,-99.0,-99.0
8374,70.0,-99.0,15.0,15.0,-99.0,-99.0
8376,70.0,-99.0,15.0,15.0,-99.0,-99.0
8377,70.0,-99.0,15.0,15.0,-99.0,-99.0

In [166]:
# o_important_attractive * o_score_attractive
def rating(data, important, score):
  if data[score] == -99:
    return -99
  elif data[important] == -99:
    return -99
  else:
    return data[important] * data[score]

In [58]:
dating_df.apply(lambda x : rating(x, 'o_important_attractive','o_score_attractive'), axis=1)

0       210.000000
1       420.000000
2       190.000000
3       210.000000
4       240.000000
           ...
8372     80.000000
8373    105.263158
8374    300.000000
8376     50.000000
8377    160.000000
Length: 8130, dtype: float64

In [167]:
i_score

['i_score_attractive',
 'i_score_sincere',
 'i_score_intelligence',
 'i_score_funny',
 'i_score_ambition',
 'i_score_shared_interests']

In [168]:
o_score

['o_score_attractive',
 'o_score_sincere',
 'o_score_intelligence',
 'o_score_funny',
 'o_score_ambitous',
 'o_score_shared_interests']

In [169]:
for i, j in zip(i_important,i_score):
  print(i,j)

i_important_attractive i_score_attractive
i_important_sincere i_score_sincere
i_important_intellicence i_score_intelligence
i_important_funny i_score_funny
i_important_ambtition i_score_ambition
i_important_shared_interests i_score_shared_interests

In [170]:
o_rating = ['o_rating_attractive',
 'o_rating_sincere',
 'o_rating_intelligence',
 'o_rating_funny',
 'o_rating_ambitous',
 'o_rating_shared_interests']

In [171]:
i_rating = ['i_rating_attractive',
 'i_rating_sincere',
 'i_rating_intelligence',
 'i_rating_funny',
 'i_rating_ambition',
 'i_rating_shared_interests']

In [172]:
# k에는 o_rating 이름이 받아줌
for i,j, k in zip(o_important, o_score, o_rating):
  dating_df[k] = dating_df.apply(lambda x : rating(x,i,j), axis=1)

In [173]:
dating_df.head()

,gender,age,age_o,race,race_o,importance_same_race,importance_same_religion,o_important_attractive,o_important_sincere,o_important_intelligence,o_important_funny,o_important_ambitious,o_important_shared_interests,o_score_attractive,o_score_sincere,o_score_intelligence,o_score_funny,o_score_ambitous,o_score_shared_interests,i_important_attractive,i_important_sincere,i_important_intellicence,i_important_funny,i_important_ambtition,i_important_shared_interests,i_score_attractive,i_score_sincere,i_score_intelligence,i_score_funny,i_score_ambition,i_score_shared_interests,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,match,age_gap,age_gap_dir,same_race,same_race_point,o_rating_attractive,o_rating_sincere,o_rating_intelligence,o_rating_funny,o_rating_ambitous,o_rating_shared_interests
0,female,21.0,27.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,35.0,20.0,20.0,20.0,0.0,5.0,6.0,8.0,8.0,8.0,8.0,6.0,15.0,20.0,20.0,15.0,15.0,15.0,6.0,9.0,7.0,7.0,6.0,5.0,0.14,3.0,2.0,7.0,6.0,0,6.0,zero,-1,-2.0,210.0,160.0,160.0,160.0,0.0,30.0
1,female,21.0,22.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,60.0,0.0,0.0,40.0,0.0,0.0,7.0,8.0,10.0,7.0,7.0,5.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,8.0,7.0,8.0,5.0,6.0,0.54,3.0,2.0,7.0,5.0,0,1.0,zero,-1,-2.0,420.0,0.0,0.0,280.0,0.0,0.0
2,female,21.0,22.0,Asian/PacificIslander/Asian-American,Asian/PacificIslander/Asian-American,2.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,10.0,10.0,10.0,10.0,10.0,10.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,8.0,9.0,8.0,5.0,7.0,0.16,3.0,2.0,7.0,-99.0,1,1.0,zero,1,2.0,190.0,180.0,190.0,180.0,140.0,120.0
3,female,21.0,23.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,30.0,5.0,15.0,40.0,5.0,5.0,7.0,8.0,9.0,8.0,9.0,8.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,6.0,8.0,7.0,6.0,8.0,0.61,3.0,2.0,7.0,6.0,1,2.0,zero,-1,-2.0,210.0,40.0,135.0,320.0,45.0,40.0
4,female,21.0,24.0,Asian/PacificIslander/Asian-American,Latino/HispanicAmerican,2.0,4.0,30.0,10.0,20.0,10.0,10.0,20.0,8.0,7.0,9.0,6.0,9.0,7.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,6.0,7.0,7.0,6.0,6.0,0.21,3.0,2.0,6.0,6.0,1,3.0,zero,-1,-2.0,240.0,70.0,180.0,60.0,90.0,140.0

In [174]:
for i,j, k in zip(i_important, i_score, i_rating):
  dating_df[k] = dating_df.apply(lambda x : rating(x,i,j), axis=1)

In [175]:
dating_df[i_rating].loc[8377][dating_df[i_rating].loc[8377] > 0].mean()

np.float64(120.0)

In [86]:
dating_df['i_rating_total'] = dating_df[i_rating].apply(lambda x : x[x > 0].mean(), axis = 1)

In [87]:
dating_df['o_rating_total'] = dating_df[i_rating].apply(lambda x : x[x > 0].mean(), axis = 1)

In [75]:
dating_df.head

,gender,age,age_o,race,race_o,importance_same_race,importance_same_religion,o_important_attractive,o_important_sincere,o_important_intelligence,o_important_funny,o_important_ambitious,o_important_shared_interests,o_score_attractive,o_score_sincere,o_score_intelligence,o_score_funny,o_score_ambitous,o_score_shared_interests,i_important_attractive,i_important_sincere,i_important_intellicence,i_important_funny,i_important_ambtition,i_important_shared_interests,...,i_score_shared_interests,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,match,age_gap,age_gap_dir,same_race,same_race_point,o_rating_attractive,o_rating_sincere,o_rating_intelligence,o_rating_funny,o_rating_ambitous,o_rating_shared_interests,i_rating_attractive,i_rating_sincere,i_rating_intelligence,i_rating_funny,i_rating_ambition,i_rating_shared_interests,o_rating_total,i_rating_total
0,female,21.0,27.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,35.0,20.0,20.0,20.0,0.0,5.0,6.0,8.0,8.0,8.0,8.0,6.0,15.0,20.0,20.0,15.0,15.0,15.0,...,5.0,0.14,3.0,2.0,7.0,6.0,0,6.0,zero,-1,-2.0,210.0,160.0,160.0,160.0,0.0,30.0,90.0,180.0,140.0,105.0,90.0,75.0,120.000000,113.333333
1,female,21.0,22.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,60.0,0.0,0.0,40.0,0.0,0.0,7.0,8.0,10.0,7.0,7.0,5.0,15.0,20.0,20.0,15.0,15.0,15.0,...,6.0,0.54,3.0,2.0,7.0,5.0,0,1.0,zero,-1,-2.0,420.0,0.0,0.0,280.0,0.0,0.0,105.0,160.0,140.0,120.0,75.0,90.0,116.666667,115.000000
2,female,21.0,22.0,Asian/PacificIslander/Asian-American,Asian/PacificIslander/Asian-American,2.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,10.0,10.0,10.0,10.0,10.0,10.0,15.0,20.0,20.0,15.0,15.0,15.0,...,7.0,0.16,3.0,2.0,7.0,-99.0,1,1.0,zero,1,2.0,190.0,180.0,190.0,180.0,140.0,120.0,75.0,160.0,180.0,120.0,75.0,105.0,166.666667,119.166667
3,female,21.0,23.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,30.0,5.0,15.0,40.0,5.0,5.0,7.0,8.0,9.0,8.0,9.0,8.0,15.0,20.0,20.0,15.0,15.0,15.0,...,8.0,0.61,3.0,2.0,7.0,6.0,1,2.0,zero,-1,-2.0,210.0,40.0,135.0,320.0,45.0,40.0,105.0,120.0,160.0,105.0,90.0,120.0,131.666667,116.666667
4,female,21.0,24.0,Asian/PacificIslander/Asian-American,Latino/HispanicAmerican,2.0,4.0,30.0,10.0,20.0,10.0,10.0,20.0,8.0,7.0,9.0,6.0,9.0,7.0,15.0,20.0,20.0,15.0,15.0,15.0,...,6.0,0.21,3.0,2.0,6.0,6.0,1,3.0,zero,-1,-2.0,240.0,70.0,180.0,60.0,90.0,140.0,75.0,120.0,140.0,105.0,90.0,90.0,130.000000,103.333333

In [88]:
# 조화평균 구하기
dating_df['rating_mean'] = 2 * dating_df['o_rating_total'] * dating_df['i_rating_total'] / (dating_df['o_rating_total'] + dating_df['i_rating_total'])

In [89]:
dating_df.head()

,gender,age,age_o,race,race_o,importance_same_race,importance_same_religion,o_important_attractive,o_important_sincere,o_important_intelligence,o_important_funny,o_important_ambitious,o_important_shared_interests,o_score_attractive,o_score_sincere,o_score_intelligence,o_score_funny,o_score_ambitous,o_score_shared_interests,i_important_attractive,i_important_sincere,i_important_intellicence,i_important_funny,i_important_ambtition,i_important_shared_interests,...,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,match,age_gap,age_gap_dir,same_race,same_race_point,o_rating_attractive,o_rating_sincere,o_rating_intelligence,o_rating_funny,o_rating_ambitous,o_rating_shared_interests,i_rating_attractive,i_rating_sincere,i_rating_intelligence,i_rating_funny,i_rating_ambition,i_rating_shared_interests,o_rating_total,i_rating_total,rating_mean
0,female,21.0,27.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,35.0,20.0,20.0,20.0,0.0,5.0,6.0,8.0,8.0,8.0,8.0,6.0,15.0,20.0,20.0,15.0,15.0,15.0,...,0.14,3.0,2.0,7.0,6.0,0,6.0,zero,-1,-2.0,210.0,160.0,160.0,160.0,0.0,30.0,90.0,180.0,140.0,105.0,90.0,75.0,113.333333,113.333333,113.333333
1,female,21.0,22.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,60.0,0.0,0.0,40.0,0.0,0.0,7.0,8.0,10.0,7.0,7.0,5.0,15.0,20.0,20.0,15.0,15.0,15.0,...,0.54,3.0,2.0,7.0,5.0,0,1.0,zero,-1,-2.0,420.0,0.0,0.0,280.0,0.0,0.0,105.0,160.0,140.0,120.0,75.0,90.0,115.000000,115.000000,115.000000
2,female,21.0,22.0,Asian/PacificIslander/Asian-American,Asian/PacificIslander/Asian-American,2.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,10.0,10.0,10.0,10.0,10.0,10.0,15.0,20.0,20.0,15.0,15.0,15.0,...,0.16,3.0,2.0,7.0,-99.0,1,1.0,zero,1,2.0,190.0,180.0,190.0,180.0,140.0,120.0,75.0,160.0,180.0,120.0,75.0,105.0,119.166667,119.166667,119.166667
3,female,21.0,23.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,30.0,5.0,15.0,40.0,5.0,5.0,7.0,8.0,9.0,8.0,9.0,8.0,15.0,20.0,20.0,15.0,15.0,15.0,...,0.61,3.0,2.0,7.0,6.0,1,2.0,zero,-1,-2.0,210.0,40.0,135.0,320.0,45.0,40.0,105.0,120.0,160.0,105.0,90.0,120.0,116.666667,116.666667,116.666667
4,female,21.0,24.0,Asian/PacificIslander/Asian-American,Latino/HispanicAmerican,2.0,4.0,30.0,10.0,20.0,10.0,10.0,20.0,8.0,7.0,9.0,6.0,9.0,7.0,15.0,20.0,20.0,15.0,15.0,15.0,...,0.21,3.0,2.0,6.0,6.0,1,3.0,zero,-1,-2.0,240.0,70.0,180.0,60.0,90.0,140.0,75.0,120.0,140.0,105.0,90.0,90.0,103.333333,103.333333,103.333333

In [94]:
select_col = list(dating_df.columns[[0,1,3]]) + list(dating_df.columns[31:])

In [95]:
select_col.remove('same_race')

In [90]:
# 불필요한 컬럼 제거
pd.Series(dating_df.columns)

0                            gender
1                               age
2                             age_o
3                              race
4                            race_o
5              importance_same_race
6          importance_same_religion
7            o_important_attractive
8               o_important_sincere
9          o_important_intelligence
10                o_important_funny
11            o_important_ambitious
12     o_important_shared_interests
13               o_score_attractive
14                  o_score_sincere
15             o_score_intelligence
16                    o_score_funny
17                 o_score_ambitous
18         o_score_shared_interests
19           i_important_attractive
20              i_important_sincere
21         i_important_intellicence
22                i_important_funny
23            i_important_ambtition
24     i_important_shared_interests
25               i_score_attractive
26                  i_score_sincere
27             i_score_intelligence
28                    i_score_funny
29                 i_score_ambition
30         i_score_shared_interests
31              interests_correlate
32    expected_happy_with_sd_people
33    expected_num_interested_in_me
34                             like
35                 guess_prob_liked
36                            match
37                          age_gap
38                      age_gap_dir
39                        same_race
40                  same_race_point
41              o_rating_attractive
42                 o_rating_sincere
43            o_rating_intelligence
44                   o_rating_funny
45                o_rating_ambitous
46        o_rating_shared_interests
47              i_rating_attractive
48                 i_rating_sincere
49            i_rating_intelligence
50                   i_rating_funny
51                i_rating_ambition
52        i_rating_shared_interests
53                   o_rating_total
54                   i_rating_total
55                      rating_mean
dtype: object

In [97]:
final_df = dating_df[select_col]

In [100]:
# object 형 데이터 원핫인코딩
final_df = pd.get_dummies(final_df)